#!/usr/bin/env bash
# Cloud Agent — repository bootstrap for QLMED local dev.
#
# Idempotent: safe to re-run. Installs system deps (PostgreSQL 16, iproute2),
# project deps, generates the Prisma client, applies migrations and writes a
# gitignored local dev .env with random dev-only secrets. Real production
# secrets NEVER live here — they belong in the Secrets panel / .env.enc.
#
# Layer split (see env-setup skill): durable repo setup lives here; the
# PostgreSQL daemon is (re)started every boot by start.sh; the Next.js dev
# server runs as the `next-dev` terminal (run-dev.sh).
set -euo pipefail

cd "$(dirname "$0")/.."
REPO_ROOT="$(pwd)"

DB_PASSWORD="qlmed_dev_local"
DB_URL="postgresql://postgres:${DB_PASSWORD}@127.0.0.1:5432/postgres?schema=public"

echo "==> [1/5] System packages (PostgreSQL, iproute2)"
if ! command -v psql >/dev/null 2>&1 || ! command -v ss >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y -qq postgresql postgresql-client iproute2
fi

echo "==> [2/5] Start PostgreSQL cluster (idempotent)"
if ! sudo pg_lsclusters 2>/dev/null | awk 'NR>1 {print $4}' | grep -q online; then
  sudo pg_ctlcluster 16 main start || true
fi
# Wait for the socket to accept connections.
for _ in $(seq 1 20); do
  if sudo -u postgres pg_isready -q 2>/dev/null; then break; fi
  sleep 1
done
sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD '${DB_PASSWORD}';" >/dev/null

echo "==> [3/5] Node dependencies (npm ci)"
npm ci

echo "==> [4/5] Local dev .env (only if missing)"
if [ ! -f "${REPO_ROOT}/.env" ]; then
  umask 077
  cat > "${REPO_ROOT}/.env" <<EOF
# Local dev env generated by .cursor/install.sh — gitignored, never committed.
# Real secrets belong in the Cursor Secrets panel / .env.enc, not here.
DATABASE_URL="${DB_URL}"
NEXTAUTH_SECRET="$(openssl rand -base64 32)"
NEXTAUTH_URL="http://localhost:3000"
ENCRYPTION_KEY="$(openssl rand -base64 32)"
QLMED_API_KEY="$(openssl rand -hex 32)"
N8N_WEBHOOK_SECRET="$(openssl rand -hex 32)"
QLMED_REQUIRE_NONEMPTY_DB="false"
QLMED_DISABLE_BACKGROUND_SERVICES="true"
EOF
  echo "    wrote ${REPO_ROOT}/.env"
else
  echo "    .env already present — left untouched"
fi

echo "==> [5/5] Prisma client + migrations"
set -a; . "${REPO_ROOT}/.env"; set +a
npx prisma generate
npx prisma migrate deploy

echo "==> install.sh done. Canonical DB: postgres @ 127.0.0.1:5432"
